### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by jamesdef** [htmlxprs/ionic-parse-todo-app#3]
Debuggin works fine, but emulating/running on both ios and Android only shows a blank screen.
Anyone experiencing the same?

**Comment by JuanjoA** [comment]
Same problem, blank screen!

**Comment by JuanjoA** [comment]
Solution:
- edit app.js and comment:
  
  ...
  // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
  // for form inputs)
  //if(window.cordova && window.cordova.plugins.Keyboard) {
  //  cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
  //}
  ...

**Comment by jamesdef** [comment]
Did the trick! Thanks!
